[package]
name = "anvil-alloy-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.8.0", features = ["full", "node-bindings"] }
alloy-chains = "0.1.48"
eyre = "0.6.12"
tokio = { version = "1.39.2", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
